name: language_picker
description: Language picker dropdown and dialog.
version: 0.4.2
homepage: https://www.wafrat.com/
repository: https://github.com/atn832/language_picker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  recase: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fonts/Roboto/